import { Box, ChakraProvider} from "@chakra-ui/react";
import Head from "next/head";
import { ReactNode } from "react";
import Navbar from "../components/NavBar";
import theme from "../utils/chakra-ui-theme";


export default function PublicLayout({ children }: { children: ReactNode }) {
  return (
    <Box minH={"100vh"} bg={"black"}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Navbar/>
        <main>{children}</main>
      </ChakraProvider>
    </Box>
  );
}
